Do not throw exception on externally invalidated cache keys
noripyt/django-cachalot pull request #169
Opened 2021-01-14 17:06 UTC by Natureshadow

[//]: # (Thanks for helping us out! Cache invalidation sucks, so your help is greatly appreciated!)

## Description

[//]: # (What're you proposing?)

This PR fixes the issue described in #120 by catching KeyErrors on cache retrieval after restarts.

2021-01-14 17:25 UTC, Andrew-Chen-Wang commented
Hey @Natureshadow thanks for the PR. Do you mind adding a test case for this as well? I'm just not able to reproduce this case, including when I restart my gunicorn processes. Is this happening because of locmem? Some info would be helpful!

2021-01-14 21:03 UTC, Natureshadow commented
> Hey @Natureshadow thanks for the PR. Do you mind adding a test case for this as well? I'm just not able to reproduce this case, including when I restart my gunicorn processes. Is this happening because of locmem? Some info would be helpful!

I would indeed write a test, but I am not sure how to get the setup in question into a test case. The setup involves uwsgi and memcached. Restarting uwsgi triggers the issue; restarting memcached afterwards fixes it.

However, I think that a faulty cache backend should result in the operation being carried out without cache, no matter how the cache got faulty.

2021-01-14 21:10 UTC, Natureshadow commented
I might be able to arrange a (read-only) tmate session on an affected system, though, if that helps.

2021-01-14 21:21 UTC, Andrew-Chen-Wang commented
Ah I see. I can put in pragma nocover comment, and I don't think this is a breaking change, more or less expected? Maybe we can have a logger/Django warning to notify the user on `KeyError` that this is happening and they can silence the warning later on.

But I can't really tell why it's happening. It might just be a uwsgi problem. Not that I'm hesitant to push this out, I just can't understand why Django errors like this. Is it because of a lost connection, maybe memcached can't handle too many connections, and **are you sure you're supposed to be restarting uwsgi**? For my gunicorn process, to have zero downtime, I just start another 3 workers, do a health check, then remove the process that's handling the initial 3 workers.

Again, not hesitant, but I'd like to get some case to see why this connection fails all of a sudden to memcached.

2021-01-15 09:56 UTC, Natureshadow commented
> But I can't really tell why it's happening. It might just be a uwsgi problem. Not that I'm hesitant to push this out, I just can't understand why Django errors like this. Is it because of a lost connection, maybe memcached can't handle _too many connections_, and **are you sure you're supposed to be restarting uwsgi**? For my gunicorn process, to have zero downtime, I just start another 3 workers, do a health check, then remove the process that's handling the initial 3 workers.

Well, why should I not restart uwsgi?

That's what makes the least sense here I think — I would expect losing cache content when restarting **memcached**, but not the application; but losing cache content when restarting the appication, but not uwsgi, does not make sense to me.

And, while I agree with your way of upgrading the application, there certainly are situations where the application server needs to be restarted.

> 
> Again, not hesitant, but I'd like to get some case to see why this connection fails all of a sudden to memcached.

I'd like to find out as well…

2021-01-15 09:59 UTC, Natureshadow commented
@Andrew-Chen-Wang Can I reach you on some synchronous channel, like IRC, Matrix or XMPP?

2021-01-15 14:55 UTC, Andrew-Chen-Wang commented
I’ll be on the Discord channel waiting. Just ping me. Hopefully I won’t be
away:)

On Fri, Jan 15, 2021 at 5:00 AM Dominik George <notifications@github.com>
wrote:

> @Andrew-Chen-Wang <https://github.com/Andrew-Chen-Wang> Can I reach you
> on some synchronous channel, like IRC, Matrix or XMPP?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/noripyt/django-cachalot/pull/169#issuecomment-760795131>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLG4VSTN7ROVTLULE4UJHTS2AG2TANCNFSM4WCXS5DQ>
> .
>

2021-01-15 16:17 UTC, Natureshadow commented
> I’ll be on the Discord channel waiting. Just ping me. Hopefully I won’t be away:)

Discord (just like GitHub) is a proprietary service with discriminatory terms of use (discriminating against people under 16 years, and in GitHub's case against people in any country the US government thinks is worth less than others). GitHub is hard to get around, but I won't accept Discord's ToS on top.

Can you offer some communicaiton platform that is fit for use in a free software project?

2021-01-15 16:42 UTC, Andrew-Chen-Wang commented
Discord is a means to an end, but I can understand your negativity. It's something we can discuss. We can use freenode? Please send a newly created channel name through email at at the email located in my profile. If that doesn't work (I don't even know how to encrypt messages on there), please provide a recommendation via the email in my profile.

2021-01-24 13:33 UTC, Natureshadow commented
Signal is not free software. It is only licenced under GPL for whitewashing reasons. The platform is not open in practice.

IRC is perfectly fine. You can just query me there under my nickname Natureshadow.

2021-03-12 20:18 UTC, Andrew-Chen-Wang commented
@Natureshadow Sorry I never got around to IRC. School and work's driving me nuts. I think this should be approved and I'd like to get it published this weekend, but I'm curious which cache backend are you using that's raising a KeyError?

But besides that I will merge this tomorrow after another quick look at publish to PyPi

2021-03-12 20:19 UTC, Andrew-Chen-Wang requested changes

2021-03-12 20:19 UTC, Andrew-Chen-Wang commented on cachalot/monkey_patch.py
> +    if data:
Please write a test case for when data is None

2021-03-21 20:59 UTC, Natureshadow commented
I have no idea how to force `data` to be `None` there without mocking a broken cache backend.

The caching backend used when it failed was memcached/

2021-03-21 23:21 UTC, Andrew-Chen-Wang commented
Ah sorry you're right. I wrote that it would have `pragma: nocover` before. Duly noted.

2021-03-21 23:27 UTC, merged

2021-03-21 23:27 UTC, Andrew-Chen-Wang commented
Thanks for the contribution and sorry for such a long wait @Natureshadow

2021-03-22 08:41 UTC, jcass77 commented
Seems like it would be safer to log an error / warning when the KeyError is caught.

Silencing it altogether could make troubleshooting very difficult for users not affected by this usecase, and won’t give any indication of what is going on when keys start disappearing mysteriously...

2021-03-22 10:21 UTC, Natureshadow commented
Thank you! No worries, your responsiveness is more than adequate!

2021-03-22 13:48 UTC, Andrew-Chen-Wang commented
@jcass77 You're right. I think some type of Django warning that can be silenced but of type "error" should be added (ref: I keep forgetting what I say... https://github.com/noripyt/django-cachalot/pull/169#issuecomment-760483860)