Update requirements.txt
noripyt/django-cachalot pull request #249
Opened 2023-12-05 07:57 UTC by ckarli

Django 5.0 Support

[//]: # (Thanks for helping us out! Cache invalidation sucks, so your help is greatly appreciated!)

## Description

[//]: # (What're you proposing?)

## Rationale

[//]: # (Why should we implement it?)

2023-12-06 08:25 UTC, ckarli commented
Consolidated the pull requests.

2023-12-06 12:39 UTC, Andrew-Chen-Wang commented
please also deprecate py 3.7 and include py 3.12. much appreciated

2023-12-13 11:48 UTC, jgillard commented
I see from the last commit that updated Django support, that at least these will need updating also: README.rst, CHANGELOG.rst, docs/quickstart.rst, setup.py, tox.ini. I've never worked on this project, so am not sure what other changes might be required.

https://github.com/noripyt/django-cachalot/commit/269798692ed73ffad41d3aec100d7ec0e796969f

2023-12-25 12:05 UTC, ckarli commented
Updated the files @jgilliard mentioned.

2023-12-25 17:38 UTC, Andrew-Chen-Wang requested changes

2023-12-25 17:38 UTC, Andrew-Chen-Wang commented on tox.ini
> +    django5.0: Django>=5.9,<5.1
```suggestion
    django5.0: Django>=5.0,<5.1
```

2023-12-26 12:22 UTC, ckarli commented
Whops. Typo fixed.

2024-01-02 16:40 UTC, Andrew-Chen-Wang approved these changes

2024-01-02 16:41 UTC, Andrew-Chen-Wang commented
thanks!

2024-01-02 16:41 UTC, merged

2024-01-11 06:45 UTC, Andrew-Chen-Wang commented
Hm upon second inspection, the CI itself is not actually running Django 5.0. It's running 4.2.9?